
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdzpwlcmfudewgowmzbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkenB3bGNtZnVkZXdnb3dtemJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjY3OTgsImV4cCI6MjA1OTUwMjc5OH0.qsyoAMCjPNPhnjnD97oSoHK6YIQh-QjPWnoxw35FIm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
